### ISSUE TITLE
Proposals

### ISSUE THREAD

**Issue by andreazllin** [filippo-brigati/conventional-emoji-commit#1]
The idea is really cool!
Here are a couple changes that could make the system more understandable, in my opinion.

| Emoji 	|   Type   	| Change to 	| Reason                                                                    	|
|:-----:	|:--------:	|:---------:	|---------------------------------------------------------------------------	|
|   📈   	|   feat   	|     🆕     	| New feature, something like that I guess                                  	|
|   ⛏   	|    fix   	|     🔧     	| Seems more fitting, also the Windows version of the Pickaxe Emoji is ugly 	|
|   ♻️   	| refactor 	|           	|                                                                           	|
|   📚   	|   docs   	|           	|                                                                           	|
|   ✨   	|   style  	|           	|                                                                           	|
|   🚦   	|   test   	|           	|                                                                           	|
|   ☄️   	|   chore  	|     🧹     	| Just like house chores                                                    	|

Maybe a configuration for this? [commitlint](https://github.com/conventional-changelog/commitlint)
So when a commit happens it is checked by the linter

**Comment by andreazllin** [comment]
About the pickaxe emoji, here's an example.

On Windows, sometimes it is shown as this:
![image](https://user-images.githubusercontent.com/51273585/180854327-0439988a-cb8d-444e-a55f-9f14b72e95c3.png)

Instead of this: 
![image](https://user-images.githubusercontent.com/51273585/180854412-04657bf5-9cfd-4dcf-a5f6-fdd7c472b125.png)

**Comment by filippo-brigati** [comment]
Thanks Andrea,
the idea of using 🔧 emoji for the fix is definitely good, even the one for the feat is more pleasant, I will update the site as soon as I have time.

The configurator would be great but I don't think I have the right skills and time to learn them, but surely in September I will try to make it. 😊
